# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_language', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('pic', models.ImageField(upload_to='media/Images/')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
