# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='pic',
        ),
    ]
