# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_submoviemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubMovieModel',
        ),
    ]
