# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_delete_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seat', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
            ],
        ),
    ]
