# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
