# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0012_bookingorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.MovieModel'),
        ),
    ]
