# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_auto_20180629_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat',
        ),
    ]
