# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0015_delete_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seat', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('select_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.MovieModel')),
            ],
        ),
    ]
