# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0016_updateseat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingOrder',
        ),
    ]
