# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0017_delete_bookingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust', models.CharField(max_length=50)),
                ('movie', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
